[package]
name = "pact_matching"
version = "0.8.14"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Pact-Rust support library that implements request and response matching logic"
documentation = "https://docs.rs/pact_matching/0.5.15/pact_matching/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]
build = "build.rs"

[dependencies]
anyhow = "1.0.40"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
hex = "0.4.2"
log = "0.4"
onig = { version = "6.1.0", default-features = false }
maplit = "1.0.2"
lazy_static = "1.4.0"
semver = "0.11.0"
lenient_semver = "0.3.0"
itertools = "0.10.0"
rand = "0.8"
sxd-document = "0.3.2"
ansi_term = "0.12.1"
difference = "2.0.0"
base64 = "0.13.0"
uuid = { version = "0.8", features = ["v4"] }
indextree = "4.3"
nom = "5.1.1"
chrono = "0.4.19"
chrono-tz = "0.5"
rand_regex = "0.15"
regex-syntax = "0.6.21"
tree_magic_mini = "2"
multipart = { version = "0.17", default-features = false, features = ["server"] }
http = "0.2"
mime = "0.3.16"
bytes = { version = "1", features = ["serde"] }
fs2 = "0.4.3"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "blocking", "json"]

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
env_logger = "0.8.2"
hamcrest2 = "0.3.0"
speculate = "0.1.2"
test-env-log = "0.2.3"
ntest = "0.7.2"
pretty_assertions = "0.6.1"

[build-dependencies]
parse-zoneinfo = "0.3.0"
maplit = "1.0.2"
